export const languages = {
  home: "Home",
  books: "Books",
  article: "Articles",
  menus: "Menu",
  profile: "My Profile",
  security: "Security",
  settings: "Settings",
  period: "period",
  firstName: "First Name",
  lastName: "Last Name",
  phone: "Phone",
  image: "Image",
  btn: "Save Changes",
  heading: "Change Or Recover Your Password:",
  email: "Email",
  currentPasvord: "Current password",
  newPassword: "New Password",
  confimPassword: "Confirm Password",
  settin: 'Settings',
  dark :'Dark',
  light : 'Light',
  english : 'English',
  uzbek : 'Uzbek',
  russian : 'Russian',
  languageText : 'Language',

};

export const languagesRus = {
  home: "Дом",
  books: "Книги",
  article: "Статьи",
  menus: "Меню",
  profile: "Мой Профил",
  security: "Безопасность",
  settings: "Настройки",
  period: "период",
  firstName: "Имя",
  lastName: "Фамилия",
  phone: "Номер Телефона",
  image: "Фото",
  btn: "Сохранит изменения",
  heading: "Изменить или восстановить свой пароль:",
  email: "Эл. адрес",
  currentPasvord: "Текущий пароль",
  newPassword: "Новый пароль",
  confimPassword: "Подтвердить Пароль",
  settin : 'Настройки',
  dark       : 'Чорний',
      light  : 'Белый',
      english: 'Английский',
      uzbek : 'Узбекский',
      russian      : 'Русский',
      languageText : 'Язык',
};
export const languagesUzb = {
  home: "Uy",
  books: "Kitoblar",
  article: "Iqtiboslar",
  menus: "Menu",
  profile: "Mening Profilim",
  security: "Xafsizlik",
  settings: "Sozlamalar",
  period: "davri",
  firstName: "Ism",
  lastName: "Familiya",
  phone: "Telefon nomer",
  image: "Foto",
  btn: "O'zgartirishlarni Saqlash",
  heading: "Parolingizni o'zgartiring yoki tiklang:",
  email: "Elektron pochta",
  currentPasvord: "Joriy parol",
  newPassword: "Yangi Parol",
  confimPassword: "Parolni tasdiqlang",
  settin : 'Sozlamalar',
  dark   : 'Qora',
  light  : 'Oq',
  english: 'Inglizcha',
  uzbek        : "O'zbekcha",
  russian      : 'Ruscha',
  languageText : 'Til',
};

// firstName, lastName, phone,image, btn, home, books , article, menus, profile, security, settings, heading  ,email ,currentPasvord ,newPassword ,confimPassword, settin,  dark,  light,  english,  uzbek,  russian,  languageText
