export const languages = {
  home: "Home",
  books: "Books",
  article: "Articles",
  menus: "Menu",
  profile: "My Profile",
  security: "Security",
  settings: "Settings",
  period: "period",
  firstName: "First Name",
  lastName: "Last Name",
  phone: "Phone",
  image: "Image",
  btn: "Save Changes",
  heading: "Change Or Recover Your Password:",
  email: "Email",
  currentPasvord: "Current password",
  newPassword: "New Password",
  confimPassword: "Confirm Password",
  settin: "Settings",
  dark: "Dark",
  light: "Light",
  english: "English",
  uzbek: "Uzbek",
  russian: "Russian",
  languageText: "Language",
  addAuthor: "Add author",
  addBook: "Add book",
  signIn: 'Sign in ',
  password: 'password',
  textLogin:'Do not you have an account?',
  btnLogin: 'Next step',
  signUp:'Sign up ',
  textRegister: 'Already have an account?',
};

export const languagesRus = {
  home: "Дом",
  books: "Книги",
  article: "Статьи",
  menus: "Меню",
  profile: "Мой Профил",
  security: "Безопасность",
  settings: "Настройки",
  period: "период",
  firstName: "Имя",
  lastName: "Фамилия",
  phone: "Номер Телефона",
  image: "Фото",
  btn: "Сохранит изменения",
  heading: "Изменить или восстановить свой пароль:",
  email: "Эл. адрес",
  currentPasvord: "Текущий пароль",
  newPassword: "Новый пароль",
  confimPassword: "Подтвердить Пароль",
  settin: "Настройки",
  dark: "Чорний",
  light: "Белый",
  english: "Английский",
  uzbek: "Узбекский",
  russian: "Русский",
  languageText: "Язык",
  addAuthor: "Добавить автора",
  addBook: "Добавить книгу",
  signIn: 'Войти',
  password: 'пароль',
  textLogin:"У вас нет аккаунта?",
  btnLogin: 'Следующий шаг',
  signUp:'Подписаться ',
  textRegister: 'У вас уже есть аккаунт?',

};
export const languagesUzb = {
  home: "Bosh sahifa",
  books: "Kitoblar",
  article: "Iqtiboslar",
  menus: "Menu",
  profile: "Mening Profilim",
  security: "Xafsizlik",
  settings: "Sozlamalar",
  period: "davri",
  firstName: "Ism",
  lastName: "Familiya",
  phone: "Telefon nomer",
  image: "Foto",
  btn: "O'zgartirishlarni Saqlash",
  heading: "Parolingizni o'zgartiring yoki tiklang:",
  email: "Elektron pochta",
  currentPasvord: "Joriy parol",
  newPassword: "Yangi Parol",
  confimPassword: "Parolni tasdiqlang",
  settin: "Sozlamalar",
  dark: "Qora",
  light: "Oq",
  english: "Inglizcha",
  uzbek: "O'zbekcha",
  russian: "Ruscha",
  languageText: "Til",
  addAuthor: "Aftor qo'shish",
  addBook: "Kitob qo'shish",
  signIn: 'Tizimga kirish',
  password: 'parol',
  textLogin:"Hisobingiz yo'qmi?",
  btnLogin: "Keyingi qadam",
  signUp:"Ro'yxatdan o'tish ",
  textRegister: 'Hisobingiz bormi?',




};

// firstName, lastName, phone,image, btn, home, books , article, menus, profile, security, settings, heading  ,email ,currentPasvord ,newPassword ,confimPassword, settin,  dark,  light,  english,  uzbek,  russian,  signIn, email, password, textLogin, btnLogin, languageText headingg, textRegister
